import { AuthProvider } from "@/features/Authentication/components/AuthProvider";
import { Header } from "@/features/Header/components";
import { ChakraProvider, Container } from "@chakra-ui/react";
import React from "react";

// import { Metadata } from "next";
// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<head>
				<title>QQQ</title>
				<link rel="apple-touch-icon" sizes="32x32" href="/public/icon.png" />
				<link rel="icon" sizes="32x32" href="/public/icon.png" />
			</head>
			<body>
				{/* Layout UI */}
				<main>
					<React.StrictMode>
						<AuthProvider>
							<ChakraProvider>
								<Header></Header>
								<Container>{children}</Container>
							</ChakraProvider>
						</AuthProvider>
					</React.StrictMode>
				</main>
			</body>
		</html>
	);
}
